### ISSUE TITLE
Woocommerce bookings?

### ISSUE THREAD

**Issue by naeemnur** [skyverge/woocommerce-sequential-order-numbers#11]
It partially doesnt work with the WooCommerce Bookings plugin if i try to create a booking and assign it to order number, it throws this error: 'Invalid order ID provided'

![assign-code](https://cloud.githubusercontent.com/assets/447468/23501172/dd33627a-ff43-11e6-9203-9fd7bb3ff9a4.jpg)

**Comment by unfulvio** [comment]
hey @naeemnur which version of WC Bookings and WooCommerce are you using?

thanks!

**Comment by bekarice** [comment]
hey @naeemnur I'm afraid it looks like Bookings is only searching for order ID, rather than order number. This should be something they can easily fix, though, by changing the `$order->id` there to use `$order->get_order_number()` or allowing to search for the `_order_number` meta key instead.

Can you please raise a [support ticket](http://woocommerce.com/my-account/tickets/) with the ninjas to get this added to Bookings and point them towards this thread? I'm afraid our plugin won't be able to make this adjustment on its end. thanks!
